### ISSUE TITLE
Multiplayer Crash

### ISSUE THREAD

**Issue by LegionSkull** [przemykomo/simple-planes#16]
On my multiplayer Forge 32.0.75 server minecraft 1.16.1 when I or anyone on the server places a plane they cannot join the server beacuse of the never ending crash loop. Everyone who goes near the place where plane was placed gets into this crash loop.
I tested if crash occurs on every available version of Simple Planes o 1.16.1 and it does.
I asking for a quick answer.
Here's a Screenshot of the error that shows up when crashed by the plane:
![2020-07-27_20 23 53](https://user-images.githubusercontent.com/68871218/88580868-95f25500-d04c-11ea-8869-ea88a1f29c6c.png)

**Comment by przemykomo** [comment]
Could you send a server crashlog?

**Comment by LegionSkull** [comment]
> 
> 
> Could you send a server crashlog?

Sorry maybe I explained it wrong. I meant that only the players that got close enough to the plane are disconnected from the server and cannot join until the plane is deleted.

**Comment by przemykomo** [comment]
Then send client log and server log.

**Comment by LegionSkull** [comment]
> 
> 
> 
Here's the server log (It's super long I know. I was joining and getting kicked by the end of the log, On this log I have installed the newest available version back then)
[2020-07-27-2.log](https://github.com/przemykomo/simple-planes/files/4988134/2020-07-27-2.log)

**Comment by przemykomo** [comment]
It looks like an issue with forge itself but @adoxentor could you look at this?

**Comment by LegionSkull** [comment]
How's the case?

**Comment by adoxentor** [comment]
we need the client log

**Comment by LegionSkull** [comment]
> 
> 
> we need the client log

Im sending the pack of all my client logs from that day

[2020-07-27 client logs.zip](https://github.com/przemykomo/simple-planes/files/5010442/2020-07-27.client.logs.zip)

**Comment by adoxentor** [comment]
please try to update both client and server to the latest version, on the low chance it doesn't work kill all planes in the world on a clock while loading all visited areas, maybe a mod version change broke something.

**Comment by LegionSkull** [comment]
> 
> 
> please try to update both client and server to the latest version, on the low chance it doesn't work kill all planes in the world on a clock while loading all visited areas, maybe a mod version change broke something.

Ok, I will try it and inform you if it didn't work

**Comment by TheWhoAreYouPerson** [comment]
Our server is a version of [https://www.curseforge.com/minecraft/modpacks/slightly-vanilla-1-16/](Slightly Vanilla Flavoured) with a few mods added (notably Simple Planes, AE2, and Botania).

_Only a subset of our players_ (about half) get a similar io.netty error upon placing a plane, or spawning/loading in a region with a (stationary? haven't tested enough) plane.

Here are the server logs ([debug.log](https://github.com/przemykomo/simple-planes/files/5060546/debug.log) and [server_latest.log](https://github.com/przemykomo/simple-planes/files/5060547/server_latest.log)) and the log from a client suffering from this issue [client_latest.log](https://github.com/przemykomo/simple-planes/files/5060535/client_latest.log). Again, not all of the clients on the server are affected by this issue for some reason.

I noticed the client log says `java.lang.IllegalStateException: Invalid entity data item type for field 10 on entity PlaneEntity['Cherry Furnace Plane'/113327, l='ClientLevel', x=-86.83, y=63.00, z=-307.80]: old=Quaternion[1.0 + 0.0i + 0.0j + 0.0k](class net.minecraft.util.math.vector.Quaternion), new=Optional.empty(class java.util.Optional)`.
Could this issue be fixed by/related to the changes to `src/main/java/xyz/przemyk/simpleplanes/handler/PlaneNetworking.java` in bbb6f7c that isn't on Curseforge yet?

The specific screen the player gets upon disconnecting is 
![image](https://user-images.githubusercontent.com/5498969/89974886-f1fed100-dc29-11ea-90ea-edffbf14fd68.png)

**Comment by przemykomo** [comment]
Closing due to #17 being merged.
