### ISSUE TITLE
[Suggestion] Option to invert pitch controls

### ISSUE THREAD

**Issue by lincore81** [przemykomo/simple-planes#70]
Hi, sorry for bringing up a point you no doubt already considered, but could you possibly provide a config setting that inverts pitch/vertical controls? I'll no doubt get used to flying down when I hold `s` to 'pull back the yoke', but it may well take me a few dozen planes to get there :)

Cheers.

**Comment by evg-zhabotinsky** [comment]
I'd like to suggest an extension to that, probably as a config option that I'd call "Flight simulator controls" for obvious reasons:
1. WASD (or preferably configurable) control roll and pitch (S for up) only, *not* also yaw or throttle like they do now. Exactly the same for helicopter, i.e. S pulls nose up and D makes it tilt right.
2. Separate yaw controls to rotate planes and mostly helicopters around vertical axis, I suggest ZC (because QE are taken).
3. Space is start / throttle up, plus another key (e.g. V, probably not used too often) for throttle down / stop engine, when started and neither pressed keep some reasonable "average" throttle.

At least for me that would solve quite a few annoyances:
1. Would finally be able to pinpoint a helicopter landing! Hard to do it when you can't move slightly forward (W), back or to a side (Space+SAD) without going up quite a bit.
2. Same with plane landing, accelerating (W) on approach to the runway makes little sense, but you have to pull up (also W) to kill vertical speed, and that normally decreases horizontal speed too.
3. When engine is stopped (throttle down key when stationary in the ground) it stops eating fuel! No longer have to take it out every time I land!
4. I want to do a barrel roll! Or at least tilt by more than a few degrees for tighter turns.

I realize this isn't a flight simulator, but IMHO that's just basic QoL stuff.
